### ISSUE TITLE
message 提示框内容过长未折行显示问题优化

### ISSUE THREAD

**Issue by ZJL8** [EOITek/element#45]
建议样式：
```css
.el-message {
  align-items: flex-start;

 .el-message__icon {
    margin-top: 3px;
 }

  .el-message__content {
    flex: 1;
    line-height: 20px;
    word-break: break-all;
    word-wrap: break-word;
    white-space: pre-wrap;
    overflow : hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 10;
    -webkit-box-orient: vertical;
  }
}
```
